CFLAGS = -Wall -Wextra -O3


all: file_to_obj Lorem.txt.o

clean:
	-rm -f file_to_obj *.o *.obj *.exe

file_to_obj: file_to_obj.c main.c
	$(CC) $(CFLAGS) $(CPPFLAGS) file_to_obj.c main.c -o $@

Lorem.txt.o: file_to_obj
	./file_to_obj Lorem.txt

